services:
  # ----------------------------
  # AUTH SERVICE
  # ----------------------------
  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "5001:5001"
    env_file:
      - ./auth-service/.env.docker
    depends_on:
      - auth-mongo
      - auth-redis

  auth-mongo:
    image: mongo:7
    container_name: auth-mongo
    ports:
      - "27018:27017"
    volumes:
      - auth-mongo-data:/data/db

  auth-redis:
    image: redis:alpine
    container_name: auth-redis
    ports:
      - "6380:6379"

  # ----------------------------
  # AUDIT SERVICE
  # ----------------------------
  audit-service:
    build: ./audit-service
    container_name: audit-service
    ports:
      - "5005:5005"
    environment:
      PORT: 5005
      MONGO_URL: mongodb://audit-mongo:27017/auditdb
    depends_on:
      - audit-mongo

  audit-mongo:
    image: mongo:7
    container_name: audit-mongo
    ports:
      - "27020:27017"
    volumes:
      - audit-mongo-data:/data/db

  # ----------------------------
  # COMPETITION SERVICE
  # ----------------------------
  competition-service:
    build: ./competition-service
    container_name: competition-service
    ports:
      - "5002:5002"
    env_file:
      - ./competition-service/.env.docker
    depends_on:
      - competition-postgres

  competition-postgres:
    image: postgres:15
    container_name: competition-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: competitiondb
    ports:
      - "5433:5432"
    volumes:
      - competition-postgres-data:/var/lib/postgresql/data

volumes:
  auth-mongo-data:
  audit-mongo-data:
  competition-postgres-data:
